version: 1
formatters:
  default:
    format: "%(levelname)-8s %(name)-20s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
loggers:
  main:
    level: DEBUG
    propagate: false
    handlers: [ console ]
root:
  level: DEBUG
  handlers: [ console ]
